@NotesApi_HostAddress = https://localhost:7138

### Все заметки
GET {{NotesApi_HostAddress}}/api/notes
Accept: application/json

### Сколько заметок
GET {{NotesApi_HostAddress}}/api/notes/count
Accept: application/json

### Заметка по id
GET {{NotesApi_HostAddress}}/api/notes/1
Accept: application/json

### Создать заметку
POST {{NotesApi_HostAddress}}/api/notes
Content-Type: application/json

{
  "title": "Первая заметка",
  "content": "Текст заметки"
}

### Обновить заметку
PUT {{NotesApi_HostAddress}}/api/notes/1
Content-Type: application/json

{
  "title": "Обновлённый заголовок",
  "content": "Новый текст"
}

### Удалить заметку
DELETE {{NotesApi_HostAddress}}/api/notes/1

###